version: '3.4'

services:
  nm-webapp:
    build:
      context: .
      target: release
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["manage.py", "runserver", "0.0.0.0:8000"]
    entrypoint: "python3"
    depends_on:
      - keycloack-db
      - keycloak
      - webapp-db
    volumes:
      - .:/code
    networks:
      - local

networks:
  local:
