# Generated by Django 4.1.5 on 2023-02-12 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [
        ("app", "0001_initial"),
        ("app", "0002_alter_experience_options_alter_experience_id"),
        ("app", "0003_rename_id_experience_unique_id"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=30)),
                ("company_url", models.CharField(max_length=30)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("role", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("technologies", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
