# Generated by Django 4.1.5 on 2023-02-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("images", models.JSONField(blank=True, null=True)),
                ("links", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "basesection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.basesection",
                    ),
                ),
            ],
            bases=("app.basesection",),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "basesection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.basesection",
                    ),
                ),
            ],
            bases=("app.basesection",),
        ),
    ]
