# Generated by Django 4.1.5 on 2023-02-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_experience_options_alter_experience_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experience",
            old_name="id",
            new_name="unique_id",
        ),
    ]
